<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name_bn' => 'গরুর মাংস',
                'name_en' => 'Beef',
                'unit' => null,
                'unit_price' => 660,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খাসির মাংস',
                'name_en' => 'Mutton',
                'unit' => null,
                'unit_price' => 930,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পাকিস্তানী মুরগী জীবিত',
                'name_en' => 'Pakistani Chicken Alive',
                'unit' => null,
                'unit_price' => 275,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পাকিস্তানী মুরগী হাইব্রীড',
                'name_en' => 'Pakistani Chicken Hybrid',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ব্রয়লার মুরগী জীবিত',
                'name_en' => 'Broiler Chicken Alive',
                'unit' => null,
                'unit_price' => 190,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ডিম',
                'name_en' => 'Egg',
                'unit' => null,
                'unit_price' => 10.5,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => '২৮ নং চাল',
                'name_en' => 'Rice 28',
                'unit' => null,
                'unit_price' => 70,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খিচুড়ির চাল',
                'name_en' => 'Khichuri Rice',
                'unit' => null,
                'unit_price' => 78,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'চিনি গুড়া পোলাও চাল',
                'name_en' => 'Chinigura Polao Rice',
                'unit' => null,
                'unit_price' => 120,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'আটা',
                'name_en' => 'Flour',
                'unit' => null,
                'unit_price' => 33,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'তৈল',
                'name_en' => 'Oil',
                'unit' => null,
                'unit_price' => 180,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'মসুর ডাল',
                'name_en' => 'Lentil',
                'unit' => null,
                'unit_price' => 100,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বুটের ডাল',
                'name_en' => 'Chickpeas Dal',
                'unit' => null,
                'unit_price' => 120,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'মুগ ডাল/খেসারী',
                'name_en' => 'Mung Dal / Khesari',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'চিনি',
                'name_en' => 'Sugar',
                'unit' => null,
                'unit_price' => 118,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'নুডুলস',
                'name_en' => 'Noodles',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'কলা',
                'name_en' => 'Banana',
                'unit' => null,
                'unit_price' => 8,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পিঁয়াজ দেশী',
                'name_en' => 'Local Onion',
                'unit' => null,
                'unit_price' => 40,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'কাঁচা মরিচ',
                'name_en' => 'Green Chili',
                'unit' => null,
                'unit_price' => 30,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'আলু',
                'name_en' => 'Potato',
                'unit' => null,
                'unit_price' => 15,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বেগুন',
                'name_en' => 'Eggplant',
                'unit' => null,
                'unit_price' => 50,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'টমেটো',
                'name_en' => 'Tomato',
                'unit' => null,
                'unit_price' => 20,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পেঁপে কাঁচা',
                'name_en' => 'Papaya Green',
                'unit' => null,
                'unit_price' => 20,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ঢেঁড়শ',
                'name_en' => 'Okra',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পটল',
                'name_en' => 'Pointed Gourd',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গাজর',
                'name_en' => 'Carrot',
                'unit' => null,
                'unit_price' => 20,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'চাল কুমড়া',
                'name_en' => 'Ash Gourd',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'লাউ',
                'name_en' => 'Bottle Gourd',
                'unit' => null,
                'unit_price' => 22,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'সবুজ/লাল শাক',
                'name_en' => 'Green/Red Spinach',
                'unit' => null,
                'unit_price' => 15,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'কলমি/পালং শাক',
                'name_en' => 'Water/Spinach',
                'unit' => null,
                'unit_price' => 15,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পুই শাক',
                'name_en' => 'Malabar Spinach',
                'unit' => null,
                'unit_price' => 15,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'সিম',
                'name_en' => 'Flat Bean',
                'unit' => null,
                'unit_price' => 30,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ফুলকপি',
                'name_en' => 'Cauliflower',
                'unit' => null,
                'unit_price' => 10,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বাধাকপি',
                'name_en' => 'Cabbage',
                'unit' => null,
                'unit_price' => 7,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'শসা',
                'name_en' => 'Cucumber',
                'unit' => null,
                'unit_price' => 30,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'লেবু',
                'name_en' => 'Lemon',
                'unit' => null,
                'unit_price' => 10,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'লবণ',
                'name_en' => 'Salt',
                'unit' => null,
                'unit_price' => 37,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'আদা',
                'name_en' => 'Ginger',
                'unit' => null,
                'unit_price' => 100,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'রসুন',
                'name_en' => 'Garlic',
                'unit' => null,
                'unit_price' => 190,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গুড়া হলুদ',
                'name_en' => 'Turmeric Powder',
                'unit' => null,
                'unit_price' => 300,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গুড়া মরিচ',
                'name_en' => 'Chili Powder',
                'unit' => null,
                'unit_price' => 360,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'শুকনা মরিচ',
                'name_en' => 'Dry Chili',
                'unit' => null,
                'unit_price' => 340,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'সরিষার তৈল',
                'name_en' => 'Mustard Oil',
                'unit' => null,
                'unit_price' => 200,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ছোট এলাচ',
                'name_en' => 'Small Cardamom',
                'unit' => null,
                'unit_price' => 4800,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বড় এলাচ',
                'name_en' => 'Large Cardamom',
                'unit' => null,
                'unit_price' => 2800,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'লবঙ্গ',
                'name_en' => 'Cloves',
                'unit' => null,
                'unit_price' => 1300,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'জিরা',
                'name_en' => 'Cumin',
                'unit' => null,
                'unit_price' => 600,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'দারুচিনি',
                'name_en' => 'Cinnamon',
                'unit' => null,
                'unit_price' => 440,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'তেজ পাতা',
                'name_en' => 'Bay Leaf',
                'unit' => null,
                'unit_price' => 100,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'জয়ফল',
                'name_en' => 'Nutmeg',
                'unit' => null,
                'unit_price' => 680,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'জয়ত্রী',
                'name_en' => 'Mace',
                'unit' => null,
                'unit_price' => 2900,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পাঁচফোড়ন',
                'name_en' => 'Panch Phoron',
                'unit' => null,
                'unit_price' => 160,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'কিসমিস',
                'name_en' => 'Raisins',
                'unit' => null,
                'unit_price' => 580,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বাদাম',
                'name_en' => 'Nut',
                'unit' => null,
                'unit_price' => 140,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'আলু বোখারা',
                'name_en' => 'Alu Bukhara / Plum',
                'unit' => null,
                'unit_price' => 440,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গুড়াদুধ',
                'name_en' => 'Milk Powder',
                'unit' => null,
                'unit_price' => 170,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'টমেটো সস',
                'name_en' => 'Tomato Sauce',
                'unit' => null,
                'unit_price' => 238,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'টক দই',
                'name_en' => 'Sour Yogurt',
                'unit' => null,
                'unit_price' => 100,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বিরিয়ানী মশলা',
                'name_en' => 'Biryani Masala',
                'unit' => null,
                'unit_price' => 55,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'ঘি',
                'name_en' => 'Ghee',
                'unit' => null,
                'unit_price' => 1200,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গোল মরিচ কালো',
                'name_en' => 'Black Pepper',
                'unit' => null,
                'unit_price' => 600,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'গোল মরিচ সাদা',
                'name_en' => 'White Pepper',
                'unit' => null,
                'unit_price' => 1000,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খেজুর ডাবাস',
                'name_en' => 'Dates Dabas',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খেজুর বস্তা',
                'name_en' => 'Dates Sack',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খেজুর সাফাবি',
                'name_en' => 'Dates Safawi',
                'unit' => null,
                'unit_price' => 700,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'খেজুর ডাবাস ১ নং',
                'name_en' => 'Dates Dabas No 1',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'আপেল',
                'name_en' => 'Apple',
                'unit' => null,
                'unit_price' => 230,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'পেয়ারা',
                'name_en' => 'Guava',
                'unit' => null,
                'unit_price' => 70,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'তরমুজ',
                'name_en' => 'Watermelon',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'বুন্দিয়া',
                'name_en' => 'Bundi',
                'unit' => null,
                'unit_price' => 165,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'জিলাপি শাহী',
                'name_en' => 'Jilapi Shahi',
                'unit' => null,
                'unit_price' => 180,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'কলা মালভোগ',
                'name_en' => 'Banana Malbhog',
                'unit' => null,
                'unit_price' => 10,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'মাল্টা',
                'name_en' => 'Malta',
                'unit' => null,
                'unit_price' => null,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_bn' => 'মুড়ি',
                'name_en' => 'Puffed Rice',
                'unit' => null,
                'unit_price' => 75,
                'hall_name' => 'Shaheed Dr. Zikrul Haque Hall',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
